version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=development
